<?php $posts = $this->getPosts(); ?>
<?php if(count($posts)): ?>
	<?php foreach ($posts as $post): ?>
<div class="postWrapper">
    <div class="postTitle">
        <h2><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle();?></a></h2>
		<h3><?php echo $post->getCreatedTime(); ?></h3>
    </div>
    <div class="postContent">
    	<div class="shorttext"><?php echo $post->getShortContent(); ?></div>
    	<div class="fulltext" style="display:none"><?php echo $post->getPostContent(); ?></div>
    	<input type="button" value="подробнее" class="switchtext">
    </div>
	<?php echo $this->getBookmarkHtml($post) ?>
	<div class="tags"><?php echo Mage::getBlockSingleton('faq/faq')->getTagsHtml($post) ?></div>
	<div class="postDetails">
		<?php if($this->getCommentsEnabled()): ?>
		<?php echo $post->getCommentCount(); ?> <a href="<?php echo $post->getAddress(); ?>#commentBox" >Comments</a> | 
		<?php endif; ?>
		<?php $postCats = $post->getCats(); ?>
		<?php if(!empty($postCats)):?>
			<?php echo Mage::helper('faq')->__('Posted in');?>
			<?php foreach($postCats as $title=>$url): ?>
				<a href="<?php echo $url; ?>"><?php echo $title; ?></a> 
			<?php endforeach;?> 
        <?php else:?>
        	 <?php echo Mage::helper('faq')->__('Posted');?>
        <?php endif;?><?php echo$this->__("By");?> <?php echo $post->getUser(); ?></div>
</div>
	<?php endforeach; ?>
<?php else: ?>  
<?php echo Mage::helper('faq')->__('No Posts in this Category.');?>
<?php endif; ?>
<?php $this->getPages(); ?>
<script language="javascript">
$j(document).ready(function(){
 $j('.switchtext').toggle(function(){
		$j(this).parent().children('.shorttext').hide();
		$j(this).parent().children('.fulltext').show();
	},function(){
		$j(this).parent().children('.fulltext').hide();
		$j(this).parent().children('.shorttext').show();

 }) 
});

</script>