<?if(Mage::getStoreConfig('reviews/reviews/userte')):?>
<script src="<?php echo $this->getSkinUrl('') ?>den_reviews/js/tiny_mce/tiny_mce.js"></script>
<script src="<?php echo $this->getSkinUrl('') ?>den_reviews/js/init_rte.js"></script>

<script>
	// Init rte
	Den_reviewsIntId = setInterval(
		function(){
			if(typeof tinyMCE != 'undefined' && $('anchor-content')){
				initRTE();
				clearInterval(Den_reviewsIntId);
			}
		}
	,500)
</script>
<?endif;?>
